# Use root/example as user/password credentials
version: '3.1'

services:

  server:
    build: ./server
    networks:
      - db_network
    volumes:
      - ./secrets:/app/secrets:ro
    environment:
      - FLASK_APP=server
      - FLASK_ENV=development

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /var/secrets/database_password.txt
    volumes:
      - ./secrets/:/var/secrets:ro
    networks:
      - db_network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      - db_network
    ports:
      - 8080:8080

networks:
  db_network:
